### ISSUE TITLE
the heatmaps

### ISSUE THREAD

**Issue by kbrock** [sim642/whatpulse#13]
Hello,

Have you had much success understanding the sqlite database?
I'm specifically looking to understand the key codes in the combo key table.
A few of them are straight forward, but others are eluding me.

Thanks. This is  a great resource

**Comment by sim642** [comment]
Since I focused on reverse-engineering the communication protocol, I probably didn't bother to investigate WhatPulse's own SQLite database contents. Or I've just forgotten about it.

Anyway, if I remember correctly, the official WhatPulse client is built with Qt, so the key codes would likely be the ones used by Qt itself and documented here: https://doc.qt.io/qt-5/qt.html#Key-enum. Or if not those, then maybe the ones used by X11, HID devices or OS kernel.

**Comment by kbrock** [comment]
thanks so much @sim642
